# Generated by Django 3.0.8 on 2020-11-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201025_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='gender',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothing',
            name='type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
