# Generated by Django 3.0.8 on 2020-11-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201109_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='clothing_type',
        ),
    ]
