# Generated by Django 3.0.8 on 2020-12-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='last',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='postalcode',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
