# Generated by Django 3.0.8 on 2020-12-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_clothing_clothing_type'),
        ('orders', '0004_auto_20201212_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Item',
        ),
    ]
